Repository ember-cli/ember-cli-terser, pull requests merged in 2020-09, with the labels that each got.

#224 Update to `terser@5` via `broccoli-uglify-sourcemap@4`
  index.js
  package.json
  yarn.lock
Labels: breaking

#225 Remove ember-try usage.
  .travis.yml
  appveyor.yml
  config/ember-try.js
  package.json
Labels: internal

#226 Remove unused test helpers.
  tests/helpers/destroy-app.js
  tests/helpers/module-for-acceptance.js
  tests/helpers/start-app.js
Labels: internal

#227 Swap to GitHub Actions for CI
  .github/workflows/ci.yml
  .travis.yml
  appveyor.yml
Labels: internal

#228 Migrate to broccoli-terser-sourcemap.
  README.md
  index.js
  package.json
  yarn.lock
Labels: enhancement

#229 Remove deep defaulting of minification options.
  README.md
  index.js
  package.json
Labels: breaking

#230 Rename to ember-cli-terser.
  README.md
  index.js
  package.json
Labels: enhancement

#231 Add automated release setup.
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal
